global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'quarkus-metrics'
    metrics_path: 'q/metrics/prometheus'
    static_configs:
      - targets: [ 'quarkus_app_1:8080', 'quarkus_app_2:8080', 'quarkus_app_3:8080' ]

remote_write:
  - url: "http://prometheus-kafka-adapter:8081/receive"