apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggregation-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aggregation-demo
  template:
    metadata:
      labels:
        app: aggregation-demo
    spec:
      containers:
        - name: aggregation-demo
          image: anejvovcakjob/aces:aggregation-demo
          ports:
            - containerPort: 8080
          env:
            - name: KUMULUZEE_STREAMING_KAFKA_PRODUCER_BOOTSTRAP_SERVERS
              value: "my-cluster-kafka-bootstrap:9092"
            - name: KUMULUZEE_STREAMING_KAFKA_CONSUMER_BOOTSTRAP_SERVERS
              value: "my-cluster-kafka-bootstrap:9092"

---

apiVersion: v1
kind: Service
metadata:
  name: aggregation-demo
spec:
  selector:
    app: aggregation-demo
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
