apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-kafka-adapter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-kafka-adapter
  template:
    metadata:
      labels:
        app: prometheus-kafka-adapter
    spec:
      containers:
        - name: prometheus-kafka-adapter
          image: telefonica/prometheus-kafka-adapter:1.9.0
          ports:
            - containerPort: 8081
          env:
            - name: KAFKA_BROKER_LIST
              value: my-cluster-kafka-bootstrap:9092
            - name: KAFKA_TOPIC
              value: prometheus_raw_data
            - name: PORT
              value: "8081"
---

apiVersion: v1
kind: Service
metadata:
  name: prometheus-kafka-adapter
spec:
  selector:
    app: prometheus-kafka-adapter
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
