apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  namespace: prometheus-demo
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      - job_name: 'quarkus-metrics'
        metrics_path: '/q/metrics/prometheus'  # Added leading slash
        static_configs:
          - targets: ['quarkus-app-1:8082', 'quarkus-app-2:8083', 'quarkus-app-3:8084']  # Changed service names to match Kubernetes DNS
