apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      - job_name: 'quarkus-metrics'
        metrics_path: '/q/metrics/prometheus'
        static_configs:
          - targets: ['quarkus-app-1:8082', 'quarkus-app-2:8083', 'quarkus-app-3:8084']
    
    remote_write:
      - url: "http://prometheus-kafka-adapter:8081/receive"
