apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkus-app-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quarkus-app-1
  template:
    metadata:
      labels:
        app: quarkus-app-1
    spec:
      containers:
        - name: quarkus-app-1
          image: anejvovcakjob/aces:microservice-demo
          ports:
            - containerPort: 8080
          env:
            - name: CUSTOMERS_API_URL
              value: "http://quarkus-app-2:8083/v1"
---
apiVersion: v1
kind: Service
metadata:
  name: quarkus-app-1
spec:
  selector:
    app: quarkus-app-1
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8080
